### ISSUE TITLE
请求修复 artist 参数不合法问题

### ISSUE THREAD

**Issue by CCKNBC** [xizeyoupan/Meting-API#12]
![image](https://github.com/xizeyoupan/Meting-API/assets/62093618/311d49ac-5e66-49a8-b1c3-061e600959ea)

正常返回API [meting.yany.ml/api?type=artist&id=5518](https://meting.yany.ml/api?type=artist&id=5518)

**Comment by xizeyoupan** [comment]
已添加功能，请求时带上server，如server=netease&type=artist&id=5518
