### ISSUE TITLE
使用 docker部署后出现问题

### ISSUE THREAD

**Issue by sakurasep** [xizeyoupan/Meting-API#13]
Trace: TypeError: Cannot read properties of undefined (reading 'trackIds')
    at get_playlist2 (file:///app/dist/deno.js:2393:31)
    at async Object.handle2 [as handle] (file:///app/dist/deno.js:2493:16)
    at async api_default (file:///app/dist/deno.js:2581:14)
    at async file:///app/dist/deno.js:3952:5
    at async file:///app/dist/deno.js:3996:7
    at async file:///app/dist/deno.js:3898:50
    at async Server.#respond (https://deno.land/std@0.191.0/http/server.ts:299:18)
    at Hono.errorHandler (file:///app/dist/deno.js:3764:15)
    at file:///app/dist/deno.js:2940:27
    at async file:///app/dist/deno.js:3952:5
    at async file:///app/dist/deno.js:3996:7
    at async file:///app/dist/deno.js:3898:50
    at async Server.#respond (https://deno.land/std@0.191.0/http/server.ts:299:18)
  --> GET /api [31m500[0m 138ms

/test 是没问题的，不知道这是出了什么问题

**Comment by xizeyoupan** [comment]
访问的完整url是？

**Comment by sakurasep** [comment]
> 访问的完整url是？

https://music.sakurasep.club/api?server=netease&type=playlist&id=7471941343
<img width="212" alt="image" src="https://github.com/xizeyoupan/Meting-API/assets/70024132/56e31673-d7cb-4b49-b6a2-8f5e7d098132">

**Comment by sakurasep** [comment]
还有就是 只是网易云歌单和歌曲出现问题 
<img width="509" alt="image" src="https://github.com/xizeyoupan/Meting-API/assets/70024132/a85ba9d6-cb08-4795-8872-f72473ef5753">
后台日志好像有需要验证登录后才能进行下一步

**Comment by sakurasep** [comment]
```
{
  code: -462,
  data: {
    actionCode: null,
    verifyType: 40,
    verifyId: 1007602,
    verifyUrl: "https://st.music.163.com/encrypt-pages",
    blockText: "验证成功后，可进行下一步操作哦~",
    verifyToken: "00.40.59deb5295d6972875a23f4420a0d8a33.3248536926",
    btnText: "",
    orpheusUrl: "",
    frontRuleIds: null,
    params: { event_id: "00388300470300061752", sign: "85cc66427777b95eda5135d05c64c33a" },
    url: "https://st.music.163.com/encrypt-pages?params=%7B%22sign%22%3A%2285cc66427777b95eda5135d05c64c33a%22...",
    urlAutoOpen: 0,
    orpheusUrlParamAppend: null
  },
  message: "请完成验证操作"
}
```

**Comment by xizeyoupan** [comment]
目前好像能访问。这问题可能是你的ip被标记了，最简单的方法是登录网页网易云自行验证一遍，或者过个一两天看看

**Comment by sakurasep** [comment]
> 这问题可能是你的ip被标记了，最简单的方法是登录网页网易云自行验证一遍，或者过个一两天看看

原来如此 那我感觉大概率就是IP 被标记了，因为我这个服务器用了好久了，感谢你的解答
