### ISSUE TITLE
cookie修改

### ISSUE THREAD

**Issue by lzh-zone** [xizeyoupan/Meting-API#14]
想问下大佬，网易的cookie怎么修改，是在/src/providers/netease/util.js这个路径吗，具体怎么修改阿，cookie粘在哪阿
![屏幕截图 2023-07-26 123051](https://github.com/xizeyoupan/Meting-API/assets/102415551/96c8d5cd-f39e-4cd9-8108-00acadd937b7)
如果大佬有空回一下，谢谢啦！

**Comment by xizeyoupan** [comment]
https://github.com/xizeyoupan/Meting-API/blob/4176fb4ad7834b94859ad2b7dd8bdc1d1a483517/src/providers/netease/util.js#L52-L55

理论上可以在53行加上

```js
options.cookie ={_ntes_nnid:'value', _ntes_nuid='value' ...}
```

如果单单加上可能会很快过期。当然最好的方式是添加一个从url就可以添加cookie的接口，并在请求时自动更新。

然而由于本人并没有什么音乐平台的会员，因此不太能测试。
