### ISSUE TITLE
当 JSONP 请求的 URL 过长时，可能会导致错误

### ISSUE THREAD

**Issue by aoestone** [xizeyoupan/Meting-API#17]
如题，举例：

https://meting-ve.2333332.xyz/api?server=tencent&type=playlist&id=8911220082&r=0.2520956569496975

![image](https://github.com/xizeyoupan/Meting-API/assets/143681838/18d1d655-21cc-48c3-82bf-7f57ad6bd5ff)

请问这种情况应该如何解决？

**Comment by aoestone** [comment]
不好意思，可能是我没有表述清楚。该链接提供的 API 服务返回确实没有问题，但是当页面引入 meting-js 标签后，通过 JSONP 请求 URL（@qq_get_url_from_json）时，会出现错误。

<meting-js id="8911220082" server="tencent" type="playlist"></meting-js>

如果页面也能正确显示播放器的话，可能是浏览器对 URL 的长度限制不同？我的浏览器是：Chrome 116.0.5845.141

[该链接](https://meting-ve.2333332.xyz/api?server=tencent&type=playlist&id=2372393267&r=0.2520956569496975)会返回一个更长的 URL（500 首歌曲的歌单）

**Comment by xizeyoupan** [comment]
https://github.com/xizeyoupan/MetingJS/commit/9e9082ea0eb79e49797c96dd85c538486bc2b6ff

已更新前端插件到2.0.5

使用

https://unpkg.com/@xizeyoupan/meting@latest/dist/Meting.min.js
https://cdn.jsdelivr.net/npm/@xizeyoupan/meting@latest/dist/Meting.min.js

或

https://cdn.jsdelivr.net/npm/@xizeyoupan/meting@2.0.5/dist/Meting.min.js
https://unpkg.com/@xizeyoupan/meting@2.0.5/dist/Meting.min.js
