### ISSUE TITLE
netease 在获取歌单数据时存在一定概率意外获取到其他歌曲

### ISSUE THREAD

**Issue by aoemon** [xizeyoupan/Meting-API#18]
https://meting-ve.2333332.xyz/api?server=netease&type=playlist&id=8712019924&r=0.004259443209829461

以上歌单只有一首歌曲，但存在一定概率意外获取到其他歌曲，返回的异常歌单数据大概在 10 首左右。

![image](https://github.com/xizeyoupan/Meting-API/assets/20963003/9c9ff9cc-d534-448b-963b-56bf2a205ed7)
![image](https://github.com/xizeyoupan/Meting-API/assets/20963003/7c55eaf7-8c79-48ce-ba39-6623aec343ab)

可以访问[该链接](https://worker-lingering-leaf-caf4.octects.workers.dev/)，它会每隔 1 秒请求一次 https://meting-ve.2333332.xyz/api?server=netease&type=playlist&id=8712019924&r=0.004259443209829461 直到获取到的歌单歌曲数量大于 1 才会返回歌单数据，平均大概等待 10 秒左右会返回异常歌单数据。

经过多次尝试，我发现官方的服务似乎没有这个问题：https://api.i-meto.com/meting/api?server=netease&type=playlist&id=8712019924&r=0.004259443209829461

**Comment by xizeyoupan** [comment]
cbc4270c981c9fb0bbc7d21fb9179f0b247873cc
