### ISSUE TITLE
HTTP 请求使用 HEAD 方法，返回响应码为 404

### ISSUE THREAD

**Issue by aoestone** [xizeyoupan/Meting-API#19]
作者你好，我有时可能需要使用 HEAD 方法只获取响应头而不获取文件内容，但响应的状态码是 404，例如：https://meting-ve.2333332.xyz/api?server=netease&type=url&id=1390417840

![image](https://github.com/xizeyoupan/Meting-API/assets/143681838/a77358c3-ef33-488b-954d-ed561aba3947)

**Comment by xizeyoupan** [comment]
https://github.com/xizeyoupan/Meting-API/commit/6bf840b807b4d7d95b919e246449e4dd4dcb8c90

**Comment by aoemon** [comment]
大佬每次都处理很快，感谢！我试了下大佬部署的服务没有问题，但尝试自己部署时出现函数调用失败的错误，截图如下：

![image](https://github.com/xizeyoupan/Meting-API/assets/20963003/c0cd8502-6989-4e36-afab-2d4df5f7599e)

![image](https://github.com/xizeyoupan/Meting-API/assets/20963003/b7910c63-00a2-4755-a11e-0529c73c4ef9)

**Comment by xizeyoupan** [comment]
> 大佬每次都处理很快，感谢！我试了下大佬部署的服务没有问题，但尝试自己部署时出现函数调用失败的错误，截图如下：
> 
> ![image](https://user-images.githubusercontent.com/20963003/270319630-c0cd8502-6989-4e36-afab-2d4df5f7599e.png)
> 
> ![image](https://user-images.githubusercontent.com/20963003/270319146-b7910c63-00a2-4755-a11e-0529c73c4ef9.png)

你是怎么部署的，访问的url是什么？另外默认api路径是`/api`

**Comment by aoemon** [comment]
我是通过点击 README 文档中给出的 [Vercel 部署按钮](https://vercel.com/import/project?template=https://github.com/xizeyoupan/Meting-API)，然后直接创建的。以下是访问 https://meting-api2.vercel.app/api 的报错信息：

![image](https://github.com/xizeyoupan/Meting-API/assets/20963003/5633acda-7690-4e5d-bfcf-ca281032b1b5)
