### ISSUE TITLE
https

### ISSUE THREAD

**Issue by gax201** [xizeyoupan/Meting-API#2]
大佬，请问一下，这个https应该怎么部署呢？我迁移到我网站上面去，http的访问不了，唉

**Comment by beimingxinglian** [comment]
![image](https://user-images.githubusercontent.com/56031542/215908519-ce70777a-6257-4767-b6b0-05cdf680667c.png)
不知道是不是nginx的配置原因，还是不能用，不知道楼上的兄弟部署好了没有

**Comment by beimingxinglian** [comment]
![image](https://user-images.githubusercontent.com/56031542/215910216-2c1b0924-01ae-4dbe-99f3-5f599fb8fe27.png)
试过的另外的写法

**Comment by gax201** [comment]
我自己写了接口服务，后来发现老用别人的接口总会出现挂掉，证书过期的可能，不如自己写了算了，就是我只写了网易云的，还有几个不知道要不要逆向，[gax201.icu](https://www.gax201.icu/)欢迎访问指导

**Comment by gax201** [comment]
这个meting-js的如何让音乐跳转到别的页面时不切歌呀，佬们

**Comment by beimingxinglian** [comment]
网站建设0基础，到处找教程，下面的链接不知道能不能解决你说的跳转页面的问题，我先收藏一波

https://blog.csdn.net/qq_46110224/article/details/109347475

**Comment by xizeyoupan** [comment]
> ![image](https://user-images.githubusercontent.com/56031542/215910216-2c1b0924-01ae-4dbe-99f3-5f599fb8fe27.png) 试过的另外的写法

反向代理设置已在README更新

**Comment by xizeyoupan** [comment]
> 这个meting-js的如何让音乐跳转到别的页面时不切歌呀，佬们

主流的方案确实是用pjax，https://github.com/defunkt/jquery-pjax

**Comment by gax201** [comment]
这个并不能解决页面刷新的问题呀，比如我翻页刷新没办法，Aplayer好像提供的有，但是是不是被meting-js重写掉了，我看别人用的Aplayer-js里面提供的api，把数据存到localstorage里面，但是到了meting-js里面不知道api在哪了

**Comment by xizeyoupan** [comment]
> 这个并不能解决页面刷新的问题呀，比如我翻页刷新没办法，Aplayer好像提供的有，但是是不是被meting-js重写掉了，我看别人用的Aplayer-js里面提供的api，把数据存到localstorage里面，但是到了meting-js里面不知道api在哪了
> 

请问别人是哪个网站，可以给个网址参考下吗🥲据我所知aplyer本身并没有这种功能，况且这好像和meting没啥关系

**Comment by xizeyoupan** [comment]
> http://xiaowenblog.com/ 他这个就可以跳转页面歌曲继续播放，操作的是aplayer的官方api

他是跳转之后直接读一下原来的数据，所以跳转时候会有卡顿，断断续续的。这种行为与meting-js不兼容。当然你可以不使用meting-js，但使用meting后端的数据来进行魔改。

**Comment by gax201** [comment]
```python
a =1
```
支不支持markdown

**Comment by gax201** [comment]
搞了一天终于搞成了
```javascript
    _loadPlayer(a) {
        let b = {audio: a, mutex: !0, lrcType: this.meta.lrcType || 3, storageName: "metingjs"};
        if (a.length) {
            let a = _objectSpread({}, b, this.config);
            for (let b in a) ("true" === a[b] || "false" === a[b]) && (a[b] = "true" === a[b]);
            let c = document.createElement("div");
            a.container = c, this.appendChild(c), this.aplayer = new APlayer(a);
            window.onbeforeunload = e => {
                //监听是否刷新，然后将音乐的索引和时间写入本地
                localStorage.setItem('music_play', this.aplayer.audio.paused)//离开前记录的音乐状态
                localStorage.setItem('music_time', this.aplayer.audio.currentTime)//离开前记录的音乐时间
                localStorage.setItem('music_index', this.aplayer.list.index)//离开前记录的音乐
            };
            let play = localStorage.getItem('music_play')
            let music_index = localStorage.getItem('music_index')
            let time = localStorage.getItem('music_time')

            //不管要不要放
            this.aplayer.list.switch(music_index);
            setTimeout(() => {
                this.aplayer.seek(parseInt(time) + 1);
            }, 300)
            //判断是否播放
            if (play === "false") {
                console.log('播放')
                this.aplayer.play();
            }

        }
    }
```
在meting-js里面加上这样一段代码就可以实现跳转页面不切歌的功能了
