### ISSUE TITLE
vercel 部署失败

### ISSUE THREAD

**Issue by xizeyoupan** [xizeyoupan/Meting-API#20]
我是通过点击 README 文档中给出的 [Vercel 部署按钮](https://vercel.com/import/project?template=https://github.com/xizeyoupan/Meting-API)，然后直接创建的。我刚才又尝试部署了一个，以下是访问 https://meting-api2.vercel.app/api 的报错信息：

![image](https://github.com/xizeyoupan/Meting-API/assets/20963003/5633acda-7690-4e5d-bfcf-ca281032b1b5)

_Originally posted by @aoemon in https://github.com/xizeyoupan/Meting-API/issues/19#issuecomment-1733616247_

**Comment by NOeSIS-yu** [comment]
我没出现问题啊dog

**Comment by xizeyoupan** [comment]
> 我没出现问题啊dog

还真是，又好了qwq
