### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by miuzkle** [xizeyoupan/Meting-API#22]
[访问网址](https://meting-dd.2333332.xyz/api?server=netease&type=playlist&id=103895515) 会出现内部错误，可能与playlist的长度过长有关

**Comment by xizeyoupan** [comment]
playlist的长度过长，无法一次请求，目前限制在前面200首。如果需要获取完整的歌单还要写一下分页功能。

**Comment by DavidingPlus** [comment]
今天部署在 deno，同样遇到了一样的问题，具体见 [https://meting-api.davidingplus.cn](https://meting-api.davidingplus.cn)。

使用作者你的可以，不知道为什么，目前仅作临时方案。
