### ISSUE TITLE
docker部署后如何修改配置

### ISSUE THREAD

**Issue by ETMN21** [xizeyoupan/Meting-API#23]
1，使用docker部署后如何将配置改为qq音乐呢我用的宝塔进入容器后如何修改找那个文件
2，想要使用api就复制api地址吗
3，不绑定域名直接ip+端口可以吗
谢谢解答，万分感谢。谢谢

**Comment by xizeyoupan** [comment]
你怎么使用的

**Comment by ETMN21** [comment]
我是想要做一个主站项目是github的imsyy然后里面有音乐播放器我想把他改为我的qq音乐歌单打开配置上面写api配置请参考Meting也就是参考你这个项目，我直接使用你的docker部署的也就是拉取镜像，运行镜像。项目可以跑起来，那么我该如何更改呢，我用的宝塔面板。

**Comment by ETMN21** [comment]
啊着发出来错别字好多啊

**Comment by xizeyoupan** [comment]
直接修改VITE_SONG_SERVER就行了。你主站也是ip访问的吗，如果主站是用域名+https访问的，音乐api就不能用ip+端口

**Comment by ETMN21** [comment]
哥能给个联系方式吗这说不清楚，我打字还慢。求求了

**Comment by xizeyoupan** [comment]
那这里正好练练你打字速度😂

**Comment by ETMN21** [comment]
行，主要怕你不在了没机会。VITE_SONG_SERVER在哪呢我进入容器内部就是常规的linux 里的 bin opt home 等文件等不知道VITE_SONG_SERVER在那个目录下，今年刚学计算机，想走网安对前端的东西一点也不懂。主站用的域名+https（域名正在备案）
所以这个项目也要绑定域名吗（我绑定一个二级域名）绑定我用反向代理可以的吧。感谢你的解答

**Comment by xizeyoupan** [comment]
![image](https://github.com/xizeyoupan/Meting-API/assets/44920131/96d7680e-cd29-4483-a12b-b32a0ba25f2a)
VITE_SONG_SERVER就是在你主站项目配置文件里，改成tencent就行了。

https页面若含有非http内容可能会有[Mixed content](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content)问题，巧了，这是网安领域。严格来说，你指的ip应该是通过ip来访问http服务。可以用反向代理，我readme都写了。

**Comment by ETMN21** [comment]
感谢，我现在还啥也不懂想走网安，但还没入门呢。那个可能我问题没写明白，我把它改为tencent 是QQ音乐，但的如何告诉它要播放我的歌单呢，也就是这个
![PixPin_2024-05-08_23-23-26](https://github.com/xizeyoupan/Meting-API/assets/152635377/5c564b0b-65f3-40d3-bd96-dbc32d80ae38)
打开后我将api复制到imsyy中，VITE_SONG_SERVER改为tencent可那也是播放这里面的qq音乐歌曲啊

![PixPin_2024-05-08_23-24-02](https://github.com/xizeyoupan/Meting-API/assets/152635377/12ae2515-58df-4b69-af1a-788c7fc527eb)
不是我自己的歌单，真是太感谢你的回复了，头疼了好久，帮我大忙了！

**Comment by xizeyoupan** [comment]
> ![image](https://private-user-images.githubusercontent.com/44920131/328941413-96d7680e-cd29-4483-a12b-b32a0ba25f2a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxODI4MDksIm5iZiI6MTcxNTE4MjUwOSwicGF0aCI6Ii80NDkyMDEzMS8zMjg5NDE0MTMtOTZkNzY4MGUtY2QyOS00NDgzLWExMmItYjMyYTBiYTI1ZjJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDE1MzUwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmYTgxOWRhNWQ3NWQxYTk5OTQ4ZTEyNDc5N2UyYjAyZWNmNjZhYzhjMDE3YzQxY2FiYTlkZTFlM2YyOGU0MjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tyt4MGdRloJ44Gt75gOV2xylK0x03grst7RCnAOeRQo) 

上面那个页面是测试用的，不用改。你要是想在你主页播放你的歌单，直接改上图的VITE_SONG_ID就行了。

**Comment by ETMN21** [comment]
##啊，那个VITE_SONG_ID在那获取呢，它是什么呢（qq音乐个人好像无法获取api，好像企业可以，不好意思我有一点愚笨）

**Comment by xizeyoupan** [comment]
VITE_SONG_ID就是播放id，是歌单的话从这里复制就好
![image](https://github.com/xizeyoupan/Meting-API/assets/44920131/3efb2ae1-706a-48e5-b596-6ed68600b0d3)

**Comment by ETMN21** [comment]
- [ ] 牛，苦死我了搜了三天，终于解决了，真是大才啊
