### ISSUE TITLE
http和https的问题

### ISSUE THREAD

**Issue by asjusdjkfd** [xizeyoupan/Meting-API#34]
[
![QQ浏览器截图20241030170628](https://github.com/user-attachments/assets/1c4ca0a5-2c78-4e86-b2b1-174a8e1179a1)
](url)
我已经设置了ssl证书，虽然这并不影响api的使用，但是它似乎并没有启用。

**Comment by xizeyoupan** [comment]
设置X-Forwarded-Host，见readme

**Comment by asjusdjkfd** [comment]
> 设置X-Forwarded-Host，见readme

好的，已解决，谢谢
