### ISSUE TITLE
aplayer的参数失效了？

### ISSUE THREAD

**Issue by beimingxinglian** [xizeyoupan/Meting-API#7]
<meting-js server="netease" type="playlist" id="7041830767" fixed="true" autoplay="true" loop="all" order="list"
        preload="auto" list-folded="ture" list-max-height="500px" lrc-type="1">
    </meting-js>

自动播放功能似乎失效了

**Comment by xizeyoupan** [comment]
我这儿没失效？

**Comment by beimingxinglian** [comment]
使用docker镜像部署的么，会不会是部署的版本不一样

**Comment by beimingxinglian** [comment]
删掉了镜像用最新的重新部署，自动播放还是无效

**Comment by xizeyoupan** [comment]
这个问题应该和理论上和后端无关，你用的是 https://github.com/metowolf/MetingJS 吗

**Comment by beimingxinglian** [comment]
docker pull intemd/meting-api:latest

**Comment by xizeyoupan** [comment]
疑似与本项目无关😢

**Comment by beimingxinglian** [comment]
修复好https之后就可以正常播放了

**Comment by beimingxinglian** [comment]
找到原因了， edge新版本会新出了个限制自动播放媒体的选项

**Comment by xizeyoupan** [comment]
你不是学设计的嘛

**Comment by beimingxinglian** [comment]
em...不是，会点python，想做个小网页，自学中
