### ISSUE TITLE
歌词无法正确获取返回值

### ISSUE THREAD

**Issue by beimingxinglian** [xizeyoupan/Meting-API#8]
![image](https://user-images.githubusercontent.com/56031542/216266639-2c64abe7-6cc2-4500-91e2-e8978bf8e6e2.png)
已经做了反代，但是歌词返回值还是http，这个看起来只能从docker内部做修改了

**Comment by xizeyoupan** [comment]
反代怎么写的

**Comment by beimingxinglian** [comment]
![image](https://user-images.githubusercontent.com/56031542/216316904-3ea495cb-c85d-4330-b8fc-2f4eb1e34260.png)

**Comment by xizeyoupan** [comment]
你看下README设下X-Forwarded-Url就行了

**Comment by beimingxinglian** [comment]
打扰了，上午部署的时候文档这一块还是空白的
